[{
  "history_id" : "k7vs00tbbze",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086324,
  "history_end_time" : 1684263086324,
  "history_notes" : null,
  "history_process" : "0ajbp0",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "8upwxh5wm9k",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086325,
  "history_end_time" : 1684263086325,
  "history_notes" : null,
  "history_process" : "tcr60i",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "howkpcshher",
  "history_input" : "#Preprocessing for test files\n\nfrom compression_and_segmentation_utils import *\nfrom fetch_data_utils import *\n\nprint(\"process is here\")\n\nprev_date, prev_month, prev_year = get_dates_with_delta(331)\n\nlon_range = (-166, -134)\nlat_range = (14, 46)\n\ndata_root = os.path.join(os.path.expanduser(\"~\"), \"ML_test\")\n\ntest_folder = os.path.join(data_root, \"cds_ssh_test_everyday_interval\")\n\nfile_pattern = \"dt_global_twosat_phy_l4_{year:04d}{month:02d}{day:02d}_vDT2021.nc\"\n\nprint(\"testdate before:\", test_folder)\n\ntest_dates, test_files = get_dates_and_files(\n    [int(prev_year)], [int(prev_month)], [int(prev_date)], test_folder, file_pattern\n)\n\n\ntest_adt, test_adt_filtered, test_masks = generate_masks_in_parallel(\n    test_files, test_dates, test=True\n)\n\ntest_subset = subset_arrays(\n    test_masks,\n    test_adt,\n    test_adt_filtered,\n    test_dates,\n    lon_range,\n    lat_range,\n    plot=True,\n    resolution_deg=0.25,\n    save_folder=test_folder,\n)\n",
  "history_output" : "process is here\ntestdate before: /home/chetana/ML_test/cds_ssh_test_everyday_interval\nFound 1 files for 2022.\n2023-05-16 18:51:37,420 WARNING We assume pixel position of grid is centered for /home/chetana/ML_test/cds_ssh_test_everyday_interval/dt_global_twosat_phy_l4_20220619_vDT2021.nc\nmultiprocessing.pool.RemoteTraceback: \n\"\"\"\nTraceback (most recent call last):\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/multiprocessing/pool.py\", line 125, in worker\n    result = (True, func(*args, **kwds))\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/multiprocessing/pool.py\", line 51, in starmapstar\n    return list(itertools.starmap(args[0], args[1]))\n  File \"/home/chetana/gw-workspace/howkpcshher/compression_and_segmentation_utils.py\", line 58, in generate_segmentation_mask_from_file\n    g, g_filtered, anticyclonic, cyclonic = identify_eddies(\n  File \"/home/chetana/gw-workspace/howkpcshher/compression_and_segmentation_utils.py\", line 77, in identify_eddies\n    g = RegularGridDataset(gridded_ssh_file, \"longitude\", \"latitude\")\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/site-packages/py_eddy_tracker/dataset/grid.py\", line 1211, in __init__\n    super().__init__(*args, **kwargs)\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/site-packages/py_eddy_tracker/dataset/grid.py\", line 307, in __init__\n    self.populate()\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/site-packages/py_eddy_tracker/dataset/grid.py\", line 311, in populate\n    self.load_general_features()\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/site-packages/py_eddy_tracker/dataset/grid.py\", line 345, in load_general_features\n    with Dataset(self.filename) as h:\n  File \"src/netCDF4/_netCDF4.pyx\", line 2307, in netCDF4._netCDF4.Dataset.__init__\n  File \"src/netCDF4/_netCDF4.pyx\", line 1925, in netCDF4._netCDF4._ensure_nc_success\nFileNotFoundError: [Errno 2] No such file or directory: b'/home/chetana/ML_test/cds_ssh_test_everyday_interval/dt_global_twosat_phy_l4_20220619_vDT2021.nc'\n\"\"\"\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/chetana/gw-workspace/howkpcshher/preprocess_test_set.py\", line 26, in <module>\n    test_adt, test_adt_filtered, test_masks = generate_masks_in_parallel(\n  File \"/home/chetana/gw-workspace/howkpcshher/compression_and_segmentation_utils.py\", line 137, in generate_masks_in_parallel\n    results = pool.starmap(generate_segmentation_mask_from_file, args)\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/multiprocessing/pool.py\", line 375, in starmap\n    return self._map_async(func, iterable, starmapstar, chunksize).get()\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/multiprocessing/pool.py\", line 774, in get\n    raise self._value\nFileNotFoundError: [Errno 2] No such file or directory: b'/home/chetana/ML_test/cds_ssh_test_everyday_interval/dt_global_twosat_phy_l4_20220619_vDT2021.nc'\n",
  "history_begin_time" : 1684263093630,
  "history_end_time" : 1684263097866,
  "history_notes" : null,
  "history_process" : "ejp9sg",
  "host_id" : "c2lqcn",
  "indicator" : "Failed"
},{
  "history_id" : "5kgzthtts3m",
  "history_input" : "# seting paths and classes for testfiles\n\nfrom link_npz_files import *\n\ndata_root = os.path.join(os.path.expanduser(\"~\"), \"ML_test\")\n\nval_folder = os.path.join(data_root, \"cds_ssh_2019_10day_interval\")\n\nval_file = os.path.join(val_folder, \"subset_pet_masks_with_adt_2019_lat14N-46N_lon166W-134W.npz\")\n\nbinary = False\nnum_classes = 2 if binary else 3\n\n",
  "history_output" : "Running",
  "history_begin_time" : 1684263099431,
  "history_end_time" : 1684263102268,
  "history_notes" : null,
  "history_process" : "wn1y5m",
  "host_id" : "c2lqcn",
  "indicator" : "Done"
},{
  "history_id" : "3bm71frytil",
  "history_input" : "# Scripts download and unzip test files\n\n# Scripts download and unzip test files\n\nimport datetime as datetime\nimport os\nfrom fetch_data_utils import *\n\n\nprev_date, prev_month, prev_year = get_dates_with_delta(331)\n\nos.chdir(os.path.expanduser(\"~\"))\ncurrent_working_dir = os.getcwd()\nroot_dir_name = \"ML_test\"\ntest_data_store = \"cds_ssh_test_everyday_interval\"\n\nroot_path = os.path.join(current_working_dir, root_dir_name)\ntest_path = os.path.join(root_path, test_data_store)\n\ncreate_directory(root_path)\ncreate_directory(test_path)\n\ntest_zip_file = download_test_date(prev_year, prev_month, prev_date)\nunzip_file(os.path.join(current_working_dir, test_zip_file), test_path)\n\n\n\n",
  "history_output" : "Something went wrong while creating folder\nSomething went wrong while creating folder\n2023-05-16 18:51:31,594 INFO Welcome to the CDS\n2023-05-16 18:51:31,595 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/satellite-sea-level-global\n2023-05-16 18:51:31,743 INFO Request is queued\n2023-05-16 18:51:32,863 INFO Request is failed\n2023-05-16 18:51:32,864 ERROR Message: the request you have submitted is not valid\n2023-05-16 18:51:32,864 ERROR Reason:  Value 'all' not valid for parameter 'variable', valid values are: daily, monthly_mean\n2023-05-16 18:51:32,864 ERROR   Traceback (most recent call last):\n2023-05-16 18:51:32,864 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,864 ERROR       result = handle_locally()\n2023-05-16 18:51:32,864 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 252, in <lambda>\n2023-05-16 18:51:32,864 ERROR       lambda: self.handle_exception(context, e),\n2023-05-16 18:51:32,864 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 383, in handle_exception\n2023-05-16 18:51:32,864 ERROR       raise exception\n2023-05-16 18:51:32,864 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,865 ERROR       result = handle_locally()\n2023-05-16 18:51:32,865 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 252, in <lambda>\n2023-05-16 18:51:32,865 ERROR       lambda: self.handle_exception(context, e),\n2023-05-16 18:51:32,865 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 365, in handle_exception\n2023-05-16 18:51:32,865 ERROR       raise exception\n2023-05-16 18:51:32,865 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,865 ERROR       result = handle_locally()\n2023-05-16 18:51:32,865 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 252, in <lambda>\n2023-05-16 18:51:32,865 ERROR       lambda: self.handle_exception(context, e),\n2023-05-16 18:51:32,865 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 406, in handle_exception\n2023-05-16 18:51:32,865 ERROR       raise exception\n2023-05-16 18:51:32,865 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,866 ERROR       result = handle_locally()\n2023-05-16 18:51:32,866 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 252, in <lambda>\n2023-05-16 18:51:32,866 ERROR       lambda: self.handle_exception(context, e),\n2023-05-16 18:51:32,866 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 132, in handle_exception\n2023-05-16 18:51:32,866 ERROR       raise exception\n2023-05-16 18:51:32,866 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,866 ERROR       result = handle_locally()\n2023-05-16 18:51:32,866 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 252, in <lambda>\n2023-05-16 18:51:32,866 ERROR       lambda: self.handle_exception(context, e),\n2023-05-16 18:51:32,866 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 132, in handle_exception\n2023-05-16 18:51:32,866 ERROR       raise exception\n2023-05-16 18:51:32,866 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,866 ERROR       result = handle_locally()\n2023-05-16 18:51:32,867 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 252, in <lambda>\n2023-05-16 18:51:32,867 ERROR       lambda: self.handle_exception(context, e),\n2023-05-16 18:51:32,867 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 132, in handle_exception\n2023-05-16 18:51:32,867 ERROR       raise exception\n2023-05-16 18:51:32,867 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,867 ERROR       result = handle_locally()\n2023-05-16 18:51:32,867 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 252, in <lambda>\n2023-05-16 18:51:32,867 ERROR       lambda: self.handle_exception(context, e),\n2023-05-16 18:51:32,867 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 132, in handle_exception\n2023-05-16 18:51:32,867 ERROR       raise exception\n2023-05-16 18:51:32,867 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 163, in _consume\n2023-05-16 18:51:32,867 ERROR       result = handle_locally()\n2023-05-16 18:51:32,867 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/dispatcher.py\", line 210, in <lambda>\n2023-05-16 18:51:32,868 ERROR       lambda: self.handle_request(context, request_data),\n2023-05-16 18:51:32,868 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/constraintsprocessor.py\", line 46, in handle_request\n2023-05-16 18:51:32,868 ERROR       constraint_type_strict)\n2023-05-16 18:51:32,868 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/constraintsengines/constraintsengine.py\", line 66, in run\n2023-05-16 18:51:32,868 ERROR       self._check_request_validity(cdsinf, request_params, constraints, constraint_type_strict)\n2023-05-16 18:51:32,868 ERROR     File \"/opt/cds/cdsinf/python/lib/cdsinf/runner/constraintsengines/constraintsengine.py\", line 162, in _check_request_validity\n2023-05-16 18:51:32,868 ERROR       \"http://copernicus-climate.eu/exc/constraints-bad-params\")\n2023-05-16 18:51:32,868 ERROR   cdsinf.exceptions.BadRequestException: Value 'all' not valid for parameter 'variable', valid values are: daily, monthly_mean\nSomething went wrong while downloading daily test data\nTraceback (most recent call last):\n  File \"/home/chetana/gw-workspace/3bm71frytil/download_test_data.py\", line 24, in <module>\n    unzip_file(os.path.join(current_working_dir, test_zip_file), test_path)\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/posixpath.py\", line 90, in join\n    genericpath._check_arg_types('join', a, *p)\n  File \"/home/chetana/anaconda3/envs/ranjan/lib/python3.10/genericpath.py\", line 152, in _check_arg_types\n    raise TypeError(f'{funcname}() argument must be str, bytes, or '\nTypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'\n",
  "history_begin_time" : 1684263087283,
  "history_end_time" : 1684263093223,
  "history_notes" : null,
  "history_process" : "znr9qa",
  "host_id" : "c2lqcn",
  "indicator" : "Failed"
},{
  "history_id" : "pehz6vizc0q",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086331,
  "history_end_time" : 1684263086331,
  "history_notes" : null,
  "history_process" : "2x5xrm",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "25dya67i7nr",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086332,
  "history_end_time" : 1684263086332,
  "history_notes" : null,
  "history_process" : "n508da",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "1hvvffgt25d",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086332,
  "history_end_time" : 1684263086332,
  "history_notes" : null,
  "history_process" : "rdt0gy",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "kg2ymls2a7j",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086332,
  "history_end_time" : 1684263086332,
  "history_notes" : null,
  "history_process" : "xdwq7e",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "j9e1r1fj9xm",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086333,
  "history_end_time" : 1684263086333,
  "history_notes" : null,
  "history_process" : "5yfzer",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "dd1x9c7fjyq",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086333,
  "history_end_time" : 1684263086333,
  "history_notes" : null,
  "history_process" : "fsy61n",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "yfus8204k1a",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086334,
  "history_end_time" : 1684263086334,
  "history_notes" : null,
  "history_process" : "sq4sw3",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "wh6g25uex8a",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086335,
  "history_end_time" : 1684263086335,
  "history_notes" : null,
  "history_process" : "shce7j",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "umbsns9220m",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086335,
  "history_end_time" : 1684263086335,
  "history_notes" : null,
  "history_process" : "g7a3zf",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "x4b08aj1ub5",
  "history_input" : "No code saved",
  "history_output" : "Skipped",
  "history_begin_time" : 1684263086336,
  "history_end_time" : 1684263086336,
  "history_notes" : null,
  "history_process" : "dhjb5i",
  "host_id" : "c2lqcn",
  "indicator" : "Skipped"
},{
  "history_id" : "0hojf7lqkv3",
  "history_input" : "#Predict eddies on testset\n\nfrom matplotlib.animation import ArtistAnimation\nfrom model_utils import *\nfrom set_summary_writer import *\n\n\nval_loader, _ = get_eddy_dataloader(\n    val_file, binary=binary, batch_size=batch_size, shuffle=False\n)\n\ndevice = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\nmodel.load_state_dict(torch.load(\"/home/chetana/tensorboard/2023-03-15_03-26/model_ckpt_68.pt\"))\nmodel.eval()\n\nwith torch.no_grad():\n    fig, ax = plt.subplots(1, 3, figsize=(25, 10))\n    artists = []\n    # loop through all SSH maps and eddy masks in 2019\n    # and run the model to generate predicted eddy masks\n    for n, (ssh_vars, seg_masks, date_indices) in enumerate(val_loader):\n        ssh_vars = ssh_vars.to(device)\n        seg_masks = seg_masks.to(device)\n        # Run the model to generate predictions\n        preds = model(ssh_vars)\n\n        # For each pixel, EddyNet outputs predictions in probabilities,\n        # so choose the channels (0, 1, or 2) with the highest prob.\n        preds = preds.argmax(dim=1)\n\n        # Loop through all SSH maps, eddy masks, and predicted masks\n        # in this minibatch and generate a video\n        preds = preds.cpu().numpy()\n        seg_masks = seg_masks.cpu().numpy()\n        ssh_vars = ssh_vars.cpu().numpy()\n        date_indices = date_indices.cpu().numpy()\n        for i in range(len(ssh_vars)):\n            date, img, mask, pred = date_indices[i], ssh_vars[i], seg_masks[i], preds[i]\n            img1, title1, img2, title2, img3, title3 = plot_eddies_on_axes(\n                date, img, mask, pred, ax[0], ax[1], ax[2]\n            )\n            artists.append([img1, title1, img2, title2, img3, title3])\n            fig.canvas.draw()\n            fig.canvas.flush_events()\n    animation = ArtistAnimation(fig, artists, interval=200, blit=True)\n    plt.close()\n\nprint(os.path.join(tensorboard_dir, \"test_predictions.gif\"))\nanimation.save(os.path.join(tensorboard_dir, \"test_predictions.gif\"), writer=\"pillow\")\n\n# HTML(animation.to_jshtml())\n\n#plot contour\n\np = preds[0].astype(np.uint8)\n\nprint(f\"Number of anticyclonic eddies: {count_eddies(p, eddy_type='anticyclonic')}\")\nprint(f\"Number of cyclonic eddies: {count_eddies(p, eddy_type='cyclonic')}\")\nprint(f\"Number of both eddies: {count_eddies(p, eddy_type='both')}\")\n\n# draw contours on the image\nthr = cv2.threshold(p, 0, 1, cv2.THRESH_BINARY)[1].astype(np.uint8)\ncontours, hierarchy = cv2.findContours(thr, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)\nimg = np.zeros(p.shape, np.uint8)\ncv2.drawContours(img, contours, -1, (255, 255, 255), 1)\nfileName = os.path.join(\"/home/chetana/plots/\",\"contours.png\")\ncv2.imwrite(fileName, img)\nplt.imshow(img, cmap=\"gray\")\nplt.axis(\"off\")\n\n# get average contour area\narea = 0\n      \n      \nfor cnt in contours:\n    area += cv2.contourArea(cnt)\narea /= len(contours)\n      \n      \nprint(f\"Average contour area: {area:.2f} sq. pixels\")\n",
  "history_output" : "Read 24 samples from /home/chetana/ML_eddie/cds_ssh_1998-2018_10day_interval/subset_pet_masks_with_adt_1998-1999_lat14N-46N_lon166W-134W.npz.\nRead 12 samples from /home/chetana/ML_eddie/cds_ssh_2019_10day_interval/subset_pet_masks_with_adt_2019_lat14N-46N_lon166W-134W.npz.\n======================================================================\nWriting Tensorboard logs to /home/chetana/tensorboard/2023-05-16_18-51\n======================================================================\nRead 12 samples from /home/chetana/ML_eddie/cds_ssh_2019_10day_interval/subset_pet_masks_with_adt_2019_lat14N-46N_lon166W-134W.npz.\n/home/chetana/tensorboard/2023-05-16_18-51/test_predictions.gif\nNumber of anticyclonic eddies: 104\nNumber of cyclonic eddies: 59\nNumber of both eddies: 119\nAverage contour area: 31.92 sq. pixels\n",
  "history_begin_time" : 1684263103889,
  "history_end_time" : 1684263125208,
  "history_notes" : null,
  "history_process" : "f6bwfv",
  "host_id" : "c2lqcn",
  "indicator" : "Done"
}]
